In [ ]:
For the first five questions, following the course of DAV

1.Basic Python Programming:
○ Write a "Hello, World!" program.
○ Practice basic data types, variables, and operators.

2. Control Structures:
○ Use loops (for, while) and conditionals (if, else) to solve simple problems.

3. NumPy Essentials:
○ Create and manipulate NumPy arrays.
○ Perform basic arithmetic operations and aggregations (mean, median, sum).

4. Data Structures with Pandas:
○ Create a DataFrame from a CSV file or dictionary.
○ Perform basic data manipulation: filtering, sorting, and indexing.

5. Basic Data Analysis:
○ Calculate descriptive statistics (mean, median, standard deviation) on a dataset
using Pandas and NumPy.

Starting From 3
NumPy Essentials: ○ Create and manipulate NumPy arrays. ○ Perform basic arithmetic operations and aggregations (mean, median, sum)

In [3]:
from numpy import random
import numpy
array = random.randint(1,50 , size=(3,4))
print("mean is " , numpy.mean(array))
print("median is " , numpy.median(array))
print("standard deviation is " , numpy.std(array))
print("\n")
print("sum of all elements is" , numpy.sum(array))
print("sum of each row is:")
for i in array:
    print(numpy.sum(i))
print("\nreshaped array is:")
numpy.reshape(array , (2,6))

mean is  21.0
median is  20.5
standard deviation is  14.702607478493965


sum of all elements is 252
sum of each row is:
61
74
117

reshaped array is:


array([[24, 33,  1,  3, 11,  4],
       [37, 22, 40, 46, 12, 19]])

In [5]:
array1 = random.randint(1,10,(3,3))
array2 = random.randint(1,10,(3,3))
array_sum = array1+array2
array_sub = array1-array2
array_dot = numpy.dot(array1,array2)
array_cross = numpy.multiply(array1,array2)
array1_transpose = numpy.transpose(array1)
array2_transpose = numpy.transpose(array2)
array1_det = numpy.linalg.det(array1)
array2_det = numpy.linalg.det(array2)

print("array1 is:\n" , array1 , "\narray2 is:" , array2)
print("\n sum is: " , array_sum , "product is: " , array_sub , "dot product is: " , array_dot , "cross product is: ",
      array_cross ,sep = "\n")
print("\n transpose of array1 is:" , array1_transpose , "\n transpose of array2 is:" , array2_transpose , sep = "\n")
print("\n det of array1 is: " , array1_det ,"\n det of array2 is: " , array2_det , sep = "\n" )
print()

if array1_det == 0:
    print("No as determinant is 0 , inverse is not possible for array 1")
else:
    print("inverse of array 1 is")
    array_inverse = numpy.linalg.inv(array1)
    print(array_inverse)
if array2_det == 0:
    print("No as determinant is 0 , inverse is not possible for array 2")
else:
    print("inverse of array 2 is")
    array_inverse = numpy.linalg.inv(array2)
    print(array_inverse)


array1 is:
 [[2 1 5]
 [4 8 5]
 [7 1 6]] 
array2 is: [[2 8 2]
 [4 6 7]
 [7 2 4]]

 sum is: 
[[ 4  9  7]
 [ 8 14 12]
 [14  3 10]]
product is: 
[[ 0 -7  3]
 [ 0  2 -2]
 [ 0 -1  2]]
dot product is: 
[[43 32 31]
 [75 90 84]
 [60 74 45]]
cross product is: 
[[ 4  8 10]
 [16 48 35]
 [49  2 24]]

 transpose of array1 is:
[[2 4 7]
 [1 8 1]
 [5 5 6]]

 transpose of array2 is:
[[2 4 7]
 [8 6 2]
 [2 7 4]]

 det of array1 is: 
-163.0

 det of array2 is: 
216.00000000000006

inverse of array 1 is
[[-0.26380368  0.00613497  0.21472393]
 [-0.06748466  0.14110429 -0.06134969]
 [ 0.3190184  -0.03067485 -0.07361963]]
inverse of array 2 is
[[ 0.0462963  -0.12962963  0.2037037 ]
 [ 0.15277778 -0.02777778 -0.02777778]
 [-0.15740741  0.24074074 -0.09259259]]


4.Data Structures with Pandas:  ○ Create a DataFrame from a CSV file or dictionary. ○ Perform basic data manipulation: filtering, sorting, and indexing.

In [12]:
import random
import pandas as pd
days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
data_dict = {}
for i in days_of_week:
    data_dict[i] = random.randint(-5 , 35)
series = pd.Series(data_dict)

print("the data is:\n" , series)
print("\nmean temperature is:" , series.mean())
print("the maximum temperature is:" , series.max() , "and the day is:" , series.idxmax())
print("the minimum temperature is:" , series.min() , "and the day is:" , series.idxmin())

print()
specific_value = float(input("Enter a temperature:"))
print("temperatures greater than" , specific_value , "are:" , (series[series>specific_value]).values)

print()
series = series * 9 / 5 + 32
print("series in farenheit is:\n" , series)

print()
print("days on which temp is greater than average is:")
mean_temp = series.mean()
d = series > mean_temp
d_index = d.index
for i in d_index:
    if d[i] == True:
        print(i)


the data is:
 Monday        2
Tuesday      16
Wednesday    28
Thursday     -1
Friday       -1
Saturday     21
Sunday       14
dtype: int64

mean temperature is: 11.285714285714286
the maximum temperature is: 28 and the day is: Wednesday
the minimum temperature is: -1 and the day is: Thursday



Enter a temperature: 22


temperatures greater than 22.0 are: [28]

series in farenheit is:
 Monday       35.6
Tuesday      60.8
Wednesday    82.4
Thursday     30.2
Friday       30.2
Saturday     69.8
Sunday       57.2
dtype: float64

days on which temp is greater than average is:
Tuesday
Wednesday
Saturday
Sunday


In [14]:
#GENERATING THE DATA
names = ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack']
rollnos = []
for i in range(1,11): rollnos.append(i)
gender = []
for i in range(1,11):
    gender_temp = random.randint(1,2)
    if random == 1: gender.append("male")
    else: gender.append("female")
marks1 , marks2, marks3 = [] , [] , []
for i in range(10):
    marks1.append(random.randint(0,100))
    marks3.append(random.randint(0,100))
    marks2.append(random.randint(0,100))
data_dict = {"rollnos" : rollnos , "gender" : gender , "marks1" : marks1 ,"marks2" : marks2 , "marks3" : marks3}

#CREATING THE DATAFRAME
df = pd.DataFrame(data_dict , index = names)
print("the dataframe is:\n" , df)
print()

#questions
df["total marks"] = df["marks1"] + df["marks2"] + df["marks3"]
print("new data frame with total marks is:\n" , df)
print()

print("the lowest in marks1 is:" , df["marks1"].min())
print("the highest in marks2 is:" , df["marks2"].min())
print("the avg in marks3 is:" , df["marks3"].mean())

df["avg"] = df["total marks"] / 3
print("the student with the highest average is: " , df["avg"].idxmax())

index = df [df["marks2"] < 40 ]
print("number of students who failed : " ,len(index))


the dataframe is:
          rollnos  gender  marks1  marks2  marks3
Alice          1  female      57      84      43
Bob            2  female       2      95      58
Charlie        3  female      21      64      33
David          4  female      57      21      69
Eve            5  female      99      44      59
Frank          6  female      90      90      57
Grace          7  female      49      16      32
Hannah         8  female      27       8      81
Ivy            9  female      64      73      57
Jack          10  female      42      84      49

new data frame with total marks is:
          rollnos  gender  marks1  marks2  marks3  total marks
Alice          1  female      57      84      43          184
Bob            2  female       2      95      58          155
Charlie        3  female      21      64      33          118
David          4  female      57      21      69          147
Eve            5  female      99      44      59          202
Frank          6  female      90

In [16]:
import csv
import pandas

# Creating and printing the data
with open('Movies.csv', mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(["Movie Name", "Language", "Genre", "Rating", "Review"])
    writer.writerow(["Parasite", "Korean", "Drama", "8.6", "Gripping"])
    writer.writerow(["The Shawshank Redemption", "English", "Drama", "9.3", "Inspiring"])
    writer.writerow(["The Godfather", "English", "Crime", "9.2", "Classic"])
    writer.writerow(["Spirited Away", "Japanese", "Animation", "8.6", "Magical"])
    writer.writerow(["Titanic", "English", "Romance", "7.8", "Heartbreaking"])
    writer.writerow(["Forrest Gump", "English", "Drama", "8.8", "Heartwarming"])
    writer.writerow(["Interstellar", "English", "Sci-Fi", "8.6", "Mind-bending"])
    writer.writerow(["Dangal", "Hindi", "Drama", "8.4", "Inspiring"])
    writer.writerow(["3 Idiots", "Hindi", "Comedy", "8.4", "Hilarious"])
    writer.writerow(["Sholay", "Hindi", "Action", "8.8", "Epic"])

with open('movies.csv', mode='r', newline='') as f:
    df = pandas.read_csv(f).set_index('Movie Name')
    display(df)
    
# Movie with highest rating
print("\nThe movie with the highest rating is", df["Rating"].idxmax())

# Sending the Hindi movies to the CSV and printing it's contents
hindi_df = df[df["Language"] == "Hindi"]
hindi_df.to_csv(path_or_buf="hindi movies.csv", sep=',')
print("\nhindi movies have been sent to 'hindi movies.csv'")
with open("hindi movies.csv","r") as f:
    print("the contents of 'hindi movies.csv' is:")
    reader = csv.reader(f)
    for i in reader:
        print(i)

Language      Genre  Rating         Review
Movie Name                                                          
Parasite                    Korean      Drama     8.6       Gripping
The Shawshank Redemption   English      Drama     9.3      Inspiring
The Godfather              English      Crime     9.2        Classic
Spirited Away             Japanese  Animation     8.6        Magical
Titanic                    English    Romance     7.8  Heartbreaking
Forrest Gump               English      Drama     8.8   Heartwarming
Interstellar               English     Sci-Fi     8.6   Mind-bending
Dangal                       Hindi      Drama     8.4      Inspiring
3 Idiots                     Hindi     Comedy     8.4      Hilarious
Sholay                       Hindi     Action     8.8           Epic


The movie with the highest rating is The Shawshank Redemption

hindi movies have been sent to 'hindi movies.csv'
the contents of 'hindi movies.csv' is:
['Movie Name', 'Language', 'Genre', 'Rating', 'Review']
['Dangal', 'Hindi', 'Drama', '8.4', 'Inspiring']
['3 Idiots', 'Hindi', 'Comedy', '8.4', 'Hilarious']
['Sholay', 'Hindi', 'Action', '8.8', 'Epic']


In [46]:
#opening and loading the dataframe
import warnings
warnings.filterwarnings('ignore')
with open("cereal.csv" , mode= "r" , newline = "") as f:
    df = df = pandas.read_csv(f)
print("The original data given is")
display(df)
df.describe
#creating the 5 number summary : min 25 meidan 75 and max
five_nos_summary_df = df.describe
print("The five number summary is")
display(five_nos_summary_df)

#replacing all -1 with column average
print("\nreplacing -1 with column average")
for i in df.columns:
    if i not in "name mfr type":
        df[i].replace(to_replace = -1 , value = df[i].mean() ,inplace = True)
display(df)

print("\nnew 5 number summary is")
five_nos_summary_df = df.describe
display(five_nos_summary_df)

#removing noisy values and replacing them with the column median
for i in df.columns:
    if i not in "name mfr type":
        q1 = df[i].quantile(0.25)
        q3= df[i].quantile(0.75)
        IQR = q3-q1
        lower_limit = q1*1.5 * IQR
        upper_limit =  q3*1.5 * IQR  
        median = df[i].median()
        for j in df[i]:
            if j<lower_limit or j>upper_limit:
                df[i].replace(to_replace = j, value=median , inplace = True)
print("\nnew 5 number summary after replacing noisy data is:")
five_nos_summary_df = df.describe
display(five_nos_summary_df)
df.shape

The original data given is


name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     5.0       6     280        25      3     1.0  0.33  68.402973  
1     8.0       8     135         0      3     1.0  1.00  33.983679  
2     7.0       5     320        25      3     1.0  0.33  59.425505  
3     8.0       0     330        25      3     1.0  0.50  93.704912  
4    14.0       8      -1        25      3     1.0  0.75  34.384843  
..    ...     ...     ...       ...    ...     ...   ...        ...  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559  

[77 rows x 16 columns]

The five number summary is


<bound method NDFrame.describe of                          name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1


replacing -1 with column average


name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars      potass  vitamins  shelf  weight  cups     rating  
0     5.0     6.0  280.000000        25      3     1.0  0.33  68.402973  
1     8.0     8.0  135.000000         0      3     1.0  1.00  33.983679  
2     7.0     5.0  320.000000        25      3     1.0  0.33  59.425505  
3     8.0     0.0  330.000000        25      3     1.0  0.50  93.704912  
4    14.0     8.0   96.077922        25      3     1.0  0.75  34.384843  
..    ...     ...         ...       ...    ...     ...   ...        ...  
72   21.0     3.0   60.000000        25      3     1.0  0.75  39.106174  
73   13.0    12.0   25.000000        25      2     1.0  1.00  27.753301  
74   17.0     3.0  115.000000        25      1     1.0  0.67  49.787445  
75   17.0     3.0  110.000000        25      1     1.0  1.00  51.592193  
76   16.0     8.0   60.000000        25      1     1.0  0.75  36.187559  

[77 rows x 16 columns]


new 5 number summary is


<bound method NDFrame.describe of                          name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1


new 5 number summary after replacing noisy data is:


<bound method NDFrame.describe of                          name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C       110        4    1     180    2.0   
1           100% Natural Bran   Q    C       110        3    5     180    2.0   
2                    All-Bran   K    C       110        4    1     180    9.0   
3   All-Bran with Extra Fiber   K    C       110        4    0     180    2.0   
4              Almond Delight   R    C       110        3    2     180    2.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        3    1     180    2.0   
73                       Trix   G    C       110        3    1     180    2.0   
74                 Wheat Chex   R    C       110        3    1     180    3.0   
75                   Wheaties   G    C       110        3    1     180    3.0   
76        Wheaties Honey Gold   G    C       110        3    1     180    2

(77, 16)